global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert_rules/*.yml

remote_write:
  - url: http://mimir:9009/api/v1/push
    send_exemplars: true
    send_native_histograms: true

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'alertmanager'
    metrics_path: /metrics
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'tempo'
    metrics_path: /metrics
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'mimir'
    metrics_path: /metrics
    static_configs:
      - targets: ['mimir:9009']

  - job_name: 'pyroscope'
    metrics_path: /metrics
    static_configs:
      - targets: ['pyroscope:4040']

  - job_name: 'alloy'
    metrics_path: /metrics
    static_configs:
      - targets: ['alloy:12345']
