apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: PROMETHEUS_DS
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: GET
  - name: Loki
    type: loki
    uid: LOKI_DS
    access: proxy
    url: http://loki:3100
  - name: Mimir
    type: prometheus
    uid: MIMIR_DS
    access: proxy
    url: http://mimir:9009/prometheus
    jsonData:
      httpMethod: GET
  - name: Tempo
    type: tempo
    uid: TEMPO_DS
    access: proxy
    url: http://tempo:3200
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: PYROSCOPE_DS
    access: proxy
    url: http://pyroscope:4040
