open_port: 8000-8999
trace_printer: disabled
log_level: INFO

otel_metrics_export:
  endpoint: http://alloy:4317
  protocol: grpc

otel_traces_export:
  endpoint: http://alloy:4317
  protocol: grpc

discovery:
  services:
    - exe_path: ".+"
  exclude_services:
    - exe_path: ".*(alloy|tempo|loki|prometheus|mimir|grafana|pyroscope|beyla).*"

network:
  enable: false
